/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar/AppBar.vue')['default']
    BaseBreadcrumb: typeof import('./components/shared_no work/BaseBreadcrumb.vue')['default']
    Calendar: typeof import('./components/Calendar/Calendar.vue')['default']
    Form: typeof import('./components/Form/Form.vue')['default']
    FullCalender: typeof import('./components/Calendar/FullCalender.vue')['default']
    LoginForm: typeof import('./components/Login/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleCalendar: typeof import('./components/Schedule/ScheduleCalendar.vue')['default']
    SharedTable: typeof import('./components/TableRecords/SharedTable.vue')['default']
    UiParentCard: typeof import('./components/shared_no work/UiParentCard.vue')['default']
  }
}
