/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Activity-Report/': RouteRecordInfo<'/Activity-Report/', '/Activity-Report', Record<never, never>, Record<never, never>>,
    '/Customers/': RouteRecordInfo<'/Customers/', '/Customers', Record<never, never>, Record<never, never>>,
    '/Departments/': RouteRecordInfo<'/Departments/', '/Departments', Record<never, never>, Record<never, never>>,
    'forbidden': RouteRecordInfo<'forbidden', '/Forbidden', Record<never, never>, Record<never, never>>,
    '/Hr/': RouteRecordInfo<'/Hr/', '/Hr', Record<never, never>, Record<never, never>>,
    '/My-Profile/': RouteRecordInfo<'/My-Profile/', '/My-Profile', Record<never, never>, Record<never, never>>,
    '/Welcome/': RouteRecordInfo<'/Welcome/', '/Welcome', Record<never, never>, Record<never, never>>,
  }
}
