/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Add/': RouteRecordInfo<'/Add/', '/Add', Record<never, never>, Record<never, never>>,
    '/Admin-Dashboard/': RouteRecordInfo<'/Admin-Dashboard/', '/Admin-Dashboard', Record<never, never>, Record<never, never>>,
    '/Calendar/': RouteRecordInfo<'/Calendar/', '/Calendar', Record<never, never>, Record<never, never>>,
    '/Clients/': RouteRecordInfo<'/Clients/', '/Clients', Record<never, never>, Record<never, never>>,
    '/Contacts/': RouteRecordInfo<'/Contacts/', '/Contacts', Record<never, never>, Record<never, never>>,
    '/Dashboard/': RouteRecordInfo<'/Dashboard/', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/Deals/': RouteRecordInfo<'/Deals/', '/Deals', Record<never, never>, Record<never, never>>,
    '/Instructor-Calendar/': RouteRecordInfo<'/Instructor-Calendar/', '/Instructor-Calendar', Record<never, never>, Record<never, never>>,
    '/Instructors/': RouteRecordInfo<'/Instructors/', '/Instructors', Record<never, never>, Record<never, never>>,
    '/Leads/': RouteRecordInfo<'/Leads/', '/Leads', Record<never, never>, Record<never, never>>,
    '/Locations/': RouteRecordInfo<'/Locations/', '/Locations', Record<never, never>, Record<never, never>>,
    '/NotSoldReasons/': RouteRecordInfo<'/NotSoldReasons/', '/NotSoldReasons', Record<never, never>, Record<never, never>>,
    '/Payment/': RouteRecordInfo<'/Payment/', '/Payment', Record<never, never>, Record<never, never>>,
    '/Post/': RouteRecordInfo<'/Post/', '/Post', Record<never, never>, Record<never, never>>,
    '/Programs/': RouteRecordInfo<'/Programs/', '/Programs', Record<never, never>, Record<never, never>>,
    '/Sources/': RouteRecordInfo<'/Sources/', '/Sources', Record<never, never>, Record<never, never>>,
    '/Student-Calendar/': RouteRecordInfo<'/Student-Calendar/', '/Student-Calendar', Record<never, never>, Record<never, never>>,
    '/Students/': RouteRecordInfo<'/Students/', '/Students', Record<never, never>, Record<never, never>>,
    '/Virtual-Office/': RouteRecordInfo<'/Virtual-Office/', '/Virtual-Office', Record<never, never>, Record<never, never>>,
  }
}
